name: qlutter
description: Qoox Color Pool Puzzle game project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.2

environment:
  sdk: '^3.9.0'

workspace:
  - packages/ui

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3 

  color_pool_puzzle:
    git:
      url: https://github.com/ziadik/color_pool_puzzle.git
      ref: main

  flutter_localizations:
    sdk: flutter
  
  ui:
    path: packages/ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.0
  flutter_lints: ^6.0.0
  slang_build_runner: ^4.5.0

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/qlutter.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/qlutter.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"

flutter:  
  uses-material-design: true

  # fonts:
  #   - family: DS Goose
  #     fonts:
  #         - asset: assets/fonts/DS Goose.ttf
  #   # - family: Permanent Marker
    #   fonts:
    #       - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    # - family: Roboto
    #     fonts:
    #       - asset: fonts/Roboto-Regular.ttf
    #       - asset: fonts/Roboto-Bold.ttf
    #         weight: 700
  assets:
    - assets/icon/
    # - assets/rive/
    - assets/data/
    
# flutter_icons:
#   android: true
#   ios: false
#   image_path: "assets/icon/icon_foreground.png"
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter_native_splash:
  color: "#121212"
  image: assets/icon/qlutter.png
  web: false
 