name: qlutter
description: Qoox Color Pool Puzzle game project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.2

environment:
  sdk: '^3.9.0'

workspace:
  - packages/ui

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3 
  
  window_manager: ^0.5.1
  flutter_localizations:
    sdk: flutter
  intl: any

  meta: any
  json_annotation: ^4.8.1

  # Utility
  collection: ^1.18.0
  async: any
  path: any
  convert: any
  path_provider: ^2.1.2
  platform_info: ^5.0.0 
  #multiline: ^3.0.0
  # rxdart: ^0.28.0-dev.0
  url_launcher: ^6.2.2

  ui:
    path: packages/ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.0
  pubspec_generator: ^5.0.0
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^6.0.0
  slang_build_runner: ^4.5.0

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon-192.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon-192.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"

flutter:  
  generate: true
  uses-material-design: true

  # fonts:
  #   - family: DS Goose
  #     fonts:
  #         - asset: assets/fonts/DS Goose.ttf
  #   # - family: Permanent Marker
    #   fonts:
    #       - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    # - family: Roboto
    #     fonts:
    #       - asset: fonts/Roboto-Regular.ttf
    #       - asset: fonts/Roboto-Bold.ttf
    #         weight: 700
  assets:
    - assets/icon/
    # - assets/rive/
    - assets/data/
    
# flutter_icons:
#   android: true
#   ios: false
#   image_path: "assets/icon/icon_foreground.png"
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter_native_splash:
  color: "#121212"
  image: assets/icon/icon-192.png
  web: false

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/ver_3/common/localization
  output_dir: lib/var_3/common/localization/generated
  use_deferred_loading: false

flutter_gen:
  output: lib/ver_3/common/constant/
  line_length: 120
 