import 'dart:math' as math;

class LevelMaps {
  static int get totalLevels => levels.length;

  static String getLevelName(int index) {
    return 'Уровень ${index + 1}';
  }

  static String sizeInfo(int level) {
    final grid = LevelMaps.levels[level];
    int width = grid.isNotEmpty ? grid[0].split(' ').length : 0;
    int height = grid.length;
    return '$width×$height';
  }

  static int width(int level) {
    final grid = LevelMaps.levels[level];
    return grid.isNotEmpty ? grid.fold<int>(grid[0].length, (min, r) => math.min(r.split(' ').length, min)) : 0;
  }

  static int height(int level) {
    final grid = LevelMaps.levels[level];
    return grid.length;
  }

  static const List<List<String>> levels = [
    // Уровень 0 (1)
    ["B B B B B B B", "B LIT T T T RIT B", "B LID D D LOD R B", "B B B B L R B", "B B B B L R B", "B B B B LID RID B", "B B B B B B B"],
    // Уровень 1 (2)
    ["B B LIT RIT B B B", "B LIT LOT ROT T RIT B", "B L N N N ROT RIT", "B L N N N ROD RID", "B LID LOD N N R B", "B B LID D D RID B", "B B B B B B B"],
    // Уровень 2
    [
      "B B B B B B B B B B",
      "B B B B B LIT T T RIT B",
      "B B B B LIT LOT N N R B",
      "B B B LIT LOT N N N ROT RIT",
      "B B LIT LOT N N N N ROD RID",
      "B LIT LOT N N N N N R B",
      "B L N N N N N N R B",
      "B L N N N N N N R B",
      "B LID LOD ROD D LOD ROD D RID B",
      "B B LID RID B LID RID B B B",
    ],
    // Уровень 3
    [
      "B B B B LIT RIT B B B B",
      "B LIT T T LOT ROT T RIT B B",
      "B L N N N N N R B B",
      "B L N N N N N R B B",
      "LIT LOT N N N N N R B B",
      "LID LOD N N N N N ROT RIT B",
      "B L N N N N N N R B",
      "B L N N N N N N R B",
      "B L N ROD LOD N ROD D RID B",
      "B LID D RID LID D RID B B B",
      "B B B B B B B B B B",
    ],
    // Уровень 4
    [
      "B B B B B LIT RIT B B B",
      "B B LIT T T LOT ROT RIT B B",
      "B LIT LOT N N N N ROT RIT B",
      "B L N N N N N N R B",
      "B L N N N N N N ROT RIT",
      "B L N N N N N N ROD RID",
      "B L N N N N N N R B",
      "B LID LOD N N N N ROD RID B",
      "B B LID D LOD ROD D RID B B",
      "B B B B LID RID B B B B",
    ],
    // Уровень 5 (6)
    [
      "B B B B B B B B B",
      "B B B LIT T RIT B B B",
      "B B B L N R B B B",
      "B LIT T LOT N ROT T T RIT",
      "LIT LOT N N N N N ROD RID",
      "LID LOD N N N N N R B",
      "B L N N N N N R B",
      "LIT LOT N N N N N R B",
      "LID LOD N N N N N R B",
      "B LID D LOD N ROD D RID B",
      "B B B L N R B B B",
      "B B B LID D RID B B B",
      "B B B B B B B B B",
    ],
    // Уровень 6
    [
      "B B B LIT RIT B B B B",
      "B B B L ROT RIT B B B",
      "B B B L N R B B B",
      "LIT T T LOT N ROT T RIT B",
      "LID LOD N N N N N ROT RIT",
      "B LID D LOD N ROD D D RID",
      "B B B L N R B B B",
      "B B B LID LOD R B B B",
      "B B B B LID RID B B B",
      "B B B B B B B B B",
    ],
    // Уровень 7
    [
      "B B B B B B LIT RIT B B B B B B",
      "B LIT T T T T LOT ROT T T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N ROT RIT",
      "LIT LOT N N N N N N N N N N ROD RID",
      "LID LOD N N ROD D LOD ROD D LOD N N R B",
      "B L N N R B LID RID B L N N R B",
      "B LID D D RID B B B B LID D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 8 (9)
    [
      "B B B B B B LIT RIT B B B B B",
      "B LIT T T T T LOT ROT T T T RIT B",
      "B L N N N N N N N N N R B",
      "LIT LOT N N N N N N N N ROD RID B",
      "LID LOD N N N N N N N N ROT RIT B",
      "B L N ROD LOD N N N N N N R B",
      "B L ROD LB LOT N N N N N N R B",
      "B L ROT LOT N N N N N N N ROT RIT",
      "B L N N N N N N N N N ROD RID",
      "B L N ROD LOD N N N N N N R B",
      "B L N ROT LOT N N N N N N R B",
      "B LID D D D LOD ROD D D D D RID B",
      "B B B B B LID RID B B B B B B",
      "B B B B B B B B B B B B B",
    ],
    // Уровень 9 (10)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N ROD RID B",
      "B L ROD LOD ROD LOD N N N N N ROT RIT B",
      "B LID RID LID RID LID D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 10 (11)
    [
      "B B B LIT RIT B B B B B B B B B",
      "B LIT T LOT ROT T T T T T T RIT B B",
      "B L N N N N N N N N N ROT RIT B",
      "B L ROD LOD ROD LOD ROD LOD N N N N R B",
      "B L R L R L R L ROD LOD N N R B",
      "B L R L R L R L R L N N R B",
      "B L R L R L R L R L N N R B",
      "B L ROT LOT R L R L R L N N R B",
      "B L N N ROT LOT ROT LOT ROT LOT N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B LID D D D D D D LOD ROD D D RID B",
      "B B B B B B B B LID RID B B B B",
    ],
    // Уровень 11
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N ROD D D D D LOD N N R B",
      "B L N ROD LB T T T RIT L N N R B",
      "B L N R L N N N R L N N R B",
      "B L N R L N N N R L N N R B",
      "B L N R L N N ROD RID L N N R B",
      "B L N R LID D D RID B L N N R B",
      "B L N ROT T T T T T RB LOD N R B",
      "B L N N N N N N N ROT LOT N R B",
      "B L N N N N N N N N N N R B",
      "B LID LOD ROD D D D D D D D D RID B",
      "B B LID RID B B B B B B B B B B",
    ],
    // Уровень 12
    [
      "B B B B B B B B LIT RIT B B B B",
      "B LIT T T T T T T LOT ROT T T RIT B",
      "B L N N N N N N N N N N ROT RIT",
      "LIT LOT N N N N N N N N N N ROD RID",
      "LID LOD N ROD LOD N ROD LOD N ROD LOD N R B",
      "B L N ROT LOT N ROT LOT N ROT LOT N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 13
    [
      "B B B B B B B B B B B B B B",
      "B B LIT T T T T T T T T RIT B B",
      "B LIT LOT N N N ROD LOD N N N ROT RIT B",
      "B L N N N N R L N N N N R B",
      "B L N N N N R L N N N N R B",
      "B L ROD LOD N N R L N N ROD LOD R B",
      "B L R L N N R L N N R L R B",
      "B L R L N N R L N N R L R B",
      "B L R LID D LOD R L ROD D RID L R B",
      "B L R B B LID RID LID RID B B L R B",
      "B L ROT T T T T T T T T LOT R B",
      "B L N N N N N N N N N N R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 14 (15)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T RIT LIT T T T T RIT LIT T RIT B",
      "B L ROD RID L N N N N R LID LOD R B",
      "B LID RID LIT LOT N N N N ROT RIT LID RID B",
      "B LIT T LOT N N N N N N ROT T RIT B",
      "B L N N N ROD D LOD N N N N R B",
      "B L N N N R B LID LOD N N N R B",
      "B L N N N ROT RIT LIT LOT N N N R B",
      "LIT LOT N N N N ROT LOT N N N N R B",
      "LID D D LOD N N N N N N ROD D RID B",
      "B LIT RIT LID LOD N N N N ROD RID LIT RIT B",
      "B L ROT RIT L N N N N R LIT LOT R B",
      "B LID D RID LID D D D D RID LID D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 15 (16)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T RIT LIT T T T T T T T RIT B",
      "B L ROD RID LID D LOD N N N N N R B",
      "B L R LIT T T LOT N ROD D LOD N R B",
      "B L R L ROD D LOD N ROT RIT L N R B",
      "B L ROT LOT R LIT LOT N N ROT LOT N R B",
      "LIT LOT N N ROT LOT N N ROD LOD N N R B",
      "LID LOD N N N N N ROD RID L ROD LOD R B",
      "B L N ROD LOD N N ROT T LOT R L R B",
      "B L N R LID LOD N N ROD D RID L R B",
      "B L N ROT RIT L N N R LIT RIT L R B",
      "B L N N ROT LOT N N ROT LOT ROT LOT R B",
      "B LID D LOD ROD D D D D D D D RID B",
      "B B B LID RID B B B B B B B B B",
    ],
    // Уровень 16
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 17
    [
      "B B B B B B LIT RIT B B B B B B",
      "B LIT T T T T LOT ROT T T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N ROT RIT",
      "B L N N N N N N N N N N N R",
      "B L N N N N N N N N N N ROD RID",
      "B L N N N N N N N N N N R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 18 (19)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B L N N ROD D D D D D D LOD R B",
      "B L N N ROT T T T T T RIT L R B",
      "B L N ROD D D D D D LOD R L R B",
      "B L N R LIT T T T RIT L R L R B",
      "B L N R L ROD LOD N R L R L R B",
      "B L N R L R L N R L R L R B",
      "B L N R L R LID D RID L R L R B",
      "B L N R L ROT T T T LOT R L R B",
      "B L N R LID D D D D D RID L R B",
      "B L N ROT T T T T T T T LOT R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 19 (20)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T RIT B LIT RIT B",
      "B L ROD D D D D D D RID LIT LOT R B",
      "B L ROT T T T T T T RIT L N R B",
      "B L ROD D D D D D D RID L N R B",
      "B L R B B B B B B B L N R B",
      "B L ROT T T T T RIT LIT T LOT N R B",
      "B L ROD D D D D RID LID D LOD N R B",
      "B L R B B B B B B B L N R B",
      "B L ROT T T T T T T RIT L N R B",
      "B L ROD D D D D D D RID L N R B",
      "B L ROT T T T T T T RIT LID LOD R B",
      "B LID D D D D D D D RID B LID RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 20
    [
      "LIT T T RIT B B B B B LIT T T T RIT",
      "L N N ROT T T T T T LOT N N N R",
      "L N N N N N N N N N N N N R",
      "LID LOD N N N N N N N N N N N R",
      "B L N N N N N N N N N N N R",
      "B L N N N N N N N N N N N R",
      "B L N N N N N N N N N N N R",
      "B L N N N N N N N N N N N R",
      "LIT LOT N N N N N N N N N N N R",
      "LID LOD N N N N N N N N N N N R",
      "B L N N N N N N N N N N N R",
      "B L N N N N N N N N N N N R",
      "B LID D LOD ROD D D D D D D LOD N R",
      "B B B LID RID B B B B B B LID D RID",
    ],
    // Уровень 21
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B LID LOD N N N N N N N N ROD RID B",
      "B LIT LOT N N N N N N N N ROT RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B LID LOD N N N N N N N N ROD RID B",
      "B LIT LOT N N N N N N N N ROT RIT B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 22
    [
      "B B B B B B B B B B B B B B",
      "LIT T T T T T T T T T T T RIT B",
      "LID LOD N N N N N N N N N N R B",
      "LIT LOT N N N N N N N N N N ROT RIT",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "LID LOD N N N N N N N N N N N R",
      "LIT LOT N N N N N N N N N N ROD RID",
      "LID LOD N N N N N N N N N N R B",
      "B LID D D D D D D LOD ROD D D RID B",
      "B B B B B B B B LID RID B B B B",
    ],
    // Уровень 23 (24)
    [
      "B B B B B B B B B B B B B B",
      "B B LIT T T T T T T T T T RIT B",
      "B LIT RB LOD N N N N N N ROD LOD R B",
      "B L ROT LOT N N N N N ROD LB LOT R B",
      "B L N N N N N N N ROT LOT N R B",
      "B L N N N ROD LOD ROD LOD N N N R B",
      "B L N N N ROT RB LB LOT N N N R B",
      "B L N N N N R L N N N N R B",
      "B L N N N N R L N N N N R B",
      "B L N N ROD D RID LID D LOD N N R B",
      "B L N N ROT T T T T LOT N N R B",
      "B L N N N N N N N N N N R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 24
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B L N N ROD D D D LOD N N N R B",
      "LIT LOT N N ROT T T T LOT N N N R B",
      "LID LOD N ROD D D D D D D LOD N R B",
      "B L N ROT T T T T T T LOT N R B",
      "B L ROD LOD ROD D D D D D D LOD R B",
      "B L ROT LOT ROT T T T T T T LOT R B",
      "B L N ROD D D D D D D LOD N R B",
      "B L N ROT T T T T T T LOT N R B",
      "B L N N ROD D D D D LOD N N R B",
      "B L N N ROT T T T T LOT N N R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 25 (26)
    [
      "B B B B B B B B B LIT RIT B B B",
      "B LIT T T T T T T T LOT ROT T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "LIT LOT N N N N N N N N N N ROT RIT",
      "LID LOD N N N N N N N N N N ROD RID",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N ROT RIT",
      "B L N N N N N N N N N N ROD RID",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B LID D D LOD ROD D D D D D D RID B",
      "B B B B LID RID B B B B B B B B",
    ],
    // Уровень 26
    [
      "B B B B B B B B B B B B B B",
      "B B B LIT T T T T T T T T RIT B",
      "B LIT RIT LID LOD N N N N N N N R B",
      "B L ROT RIT LID LOD N N N N N N R B",
      "B L N ROT RIT LID LOD N N N N N R B",
      "B L N N ROT T LOT N N N N N R B",
      "B L N N N N ROD LOD N N N N R B",
      "B L N N N N ROT RB D LOD N N R B",
      "B L N N N N N ROT RIT LID LOD N R B",
      "B L N N N N N N ROT RIT LID LOD R B",
      "B L N N N N N N N ROT RIT LID RID B",
      "B L N N N N N N N N ROT RIT B B",
      "B LID D D D D D D D D LOD R B B",
      "B B B B B B B B B B LID RID B B",
    ],
    // Уровень 27
    [
      "LIT RIT B B B B B B B B B B LIT RIT",
      "LID LB T T T T T T T T T T RB RID",
      "B L N N N N N N N ROD D LOD R B",
      "B L ROD D LOD N N N N R B L R B",
      "B L ROT T LOT N N N N ROT T LOT R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N ROD LOD N N N N N N R B",
      "B L N ROD LB LOT N N N ROD D LOD R B",
      "B L N ROT LOT N N N N ROT RIT L R B",
      "B L N N N N N N N N ROT LOT R B",
      "B L N N N N ROD LOD N N N N R B",
      "LIT RB D D D D RID LID D D D D LB RIT",
      "LID RID B B B B B B B B B B LID RID",
    ],
    // Уровень 28
    [
      "LIT T T T T T T T T T T T T RIT",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "L N N N N N N N N N N N N R",
      "LID D D D D D D D D D D D D RID",
    ],
    // Уровень 29 (30)
    [
      "LIT RIT LIT RIT LIT RIT LIT RIT LIT RIT LIT RIT B B",
      "LID LB LOT ROT LOT ROT LOT ROT LOT ROT LOT ROT RIT B",
      "LIT LOT N N N N N N N N N N ROT RIT",
      "LID LOD N N N N N N N N N N ROD RID",
      "LIT LOT N N N N N N N N N N ROT RIT",
      "LID LOD N N N N N N N N N N ROD RID",
      "LIT LOT N N N N N N N N N N ROT RIT",
      "LID LOD N N N N N N N N N N ROD RID",
      "LIT LOT N N N N N N N N N N ROT RIT",
      "LID LOD N N N N N N N N N N ROD RID",
      "B L N N N N N N N N N N ROT RIT",
      "LIT LOT N N N N N N N N N N ROD RID",
      "LID D LOD ROD LOD ROD LOD ROD LOD ROD LOD ROD LB RIT",
      "B B LID RID LID RID LID RID LID RID LID RID LID RID",
    ],
    // Уровень 30 (31)
    [
      "B B B B B B B LIT RIT B B B B B",
      "B LIT T T T T T LOT ROT T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "LIT LOT N N N N N N N N N N R B",
      "LID LOD N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "LIT LOT N N N N N N N N N N R B",
      "LID LOD ROD D D LOD N N ROD D D LOD R B",
      "B LID RID LIT RIT LID D LOD R LIT RIT LID RID B",
      "B B B LID RID B B LID RID LID RID B B B",
    ],
    // Уровень 31
    [
      "B B B B B B B LIT RIT B B B B B",
      "B LIT T T T T T LOT ROT T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N ROT RIT",
      "B L N N N N N N N N N N ROD RID",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 32
    [
      "LIT RIT B B B B LIT T T RIT B B LIT RIT",
      "LID LB T T T T LOT N N ROT T T RB RID",
      "B L N N N N N N N N N N R B",
      "LIT LOT N N N N N N N N N N R B",
      "L N N N N N N N N N N N R B",
      "LID LOD N N N N N N N N N N R B",
      "B L N N N N N N N N N N ROT RIT",
      "LIT LOT N N N N N N N N N N ROD RID",
      "LID LOD N N N N N N N N N N ROT RIT",
      "B L N N N N N N N N N N ROD RID",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "LIT RB D D D LOD ROD D D D D D LB RIT",
      "LID RID B B B LID RID B B B B B LID RID",
    ],
    // Уровень 33
    [
      "B B LIT T T RIT B B B LIT T T T RIT",
      "B B LID D LOD ROT T RIT B L ROD D D RID",
      "B B B B LID D LOD R B L R B B B",
      "B B B LIT T T LOT ROT T LOT R LIT T RIT",
      "LIT T T LOT N N N N N N R LID LOD R",
      "L ROD D LOD N N ROD LOD N N R B L R",
      "L R B L N ROD RID LID LOD N R LIT LOT R",
      "L ROT RIT L N ROT RIT LIT LOT N ROT LOT ROD RID",
      "LID D RID L N N ROT LOT N N ROD D RID B",
      "B B B L N N N N N N R B B B",
      "B B B LID LOD ROD D LOD ROD D LB T T RIT",
      "LIT T RIT LIT LOT R B L R LIT LOT ROD LOD R",
      "LID LOD ROT LOT ROD RID B L ROT LOT ROD RID L R",
      "B LID D D RID B B LID D D RID B LID RID",
    ],
    // Уровень 34 (35)
    [
      "LIT RIT LIT RIT LIT RIT LIT RIT LIT RIT LIT RIT LIT RIT",
      "LID LB RB LB RB LB RB LB RB LB RB LB RB RID",
      "LIT RB LB LOT ROT LOT ROT LOT ROT LOT ROT RB LB RIT",
      "LID LB LOT N N N N N N N N ROT RB RID",
      "LIT RB LOD N N N N N N N N ROD LB RIT",
      "LID LB LOT N N N N N N N N ROT RB RID",
      "LIT RB LOD N N N ROD LOD N N N ROD LB RIT",
      "LID LB LOT N N N ROT LOT N N N ROT RB RID",
      "LIT RB LOD N N N N N N N N ROD LB RIT",
      "LID LB LOT N N N N N N N N ROT RB RID",
      "LIT RB LOD N N N N N N N N ROD LB RIT",
      "LID LB RB LOD ROD LOD ROD LOD ROD LOD ROD LB RB RID",
      "LIT RB LB RB LB RB LB RB LB RB LB RB LB RIT",
      "LID RID LID RID LID RID LID RID LID RID LID RID LID RID",
    ],
    // Уровень 35 (36)
    [
      "B B B B LIT RIT B B LIT RIT B B B B",
      "B LIT T T LOT ROT T T LOT ROT T T RIT B",
      "LIT LOT N N N N N N N N N N R B",
      "LID LOD N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N N N N N N N N R B",
      "LIT LOT N N N N N N N N N N R B",
      "L N N N N N N N N N N N R B",
      "L N N N N N N N N N N N ROT RIT",
      "L N N N N N N N N N N N N R",
      "LID D D D D D D D D D D D D RID",
    ],
    // Уровень 36
    [
      "B B LIT RIT B B LIT RIT B B B B B B",
      "B LIT LOT R B B L ROT RIT LIT T T RIT B",
      "LIT LOT N R B B L N R L N N R B",
      "LID LOD N ROT T T LOT N R L ROD LOD R B",
      "B L N ROD LOD ROD LOD N ROT LOT ROT LOT R B",
      "B LID D RID L R LID D D LOD N ROD RID B",
      "B B B LIT LOT ROT T T T LOT N ROT RIT B",
      "B B B LID LOD ROD LOD ROD D LOD ROD LOD R B",
      "B LIT T RIT L R L ROT RIT L ROT LOT R B",
      "B L N ROT LOT ROT LOT N R L ROD LOD R B",
      "LIT LOT N ROD D D LOD N R L ROT LOT R B",
      "LID LOD N R B B L N R L N N R B",
      "B L ROD RID B B LID D RID LID D D RID B",
      "B LID RID B B B B B B B B B B B",
    ],
    // Уровень 37
    [
      "LIT T RIT B B B B B B B B LIT T RIT",
      "L N ROT T T T RIT LIT T T T LOT N R",
      "LID LOD N N N N ROT LOT N N N N ROD RID",
      "B L N ROD D D LOD ROD D D LOD N R B",
      "B L N R LIT T LOT ROT T RIT L N R B",
      "B L N R L N N N N R L N R B",
      "B LID LOD ROT LOT N N N N ROT LOT ROD RID B",
      "B LIT LOT ROD LOD N N N N ROD LOD ROT RIT B",
      "B L N R L N N N N R L N R B",
      "B L N R LID D LOD ROD D RID L N R B",
      "B L N ROT T T LOT ROT T T LOT N R B",
      "LIT LOT N N N N ROD LOD N N N N ROT RIT",
      "L N ROD D D D RID LID LOD ROD D LOD N R",
      "LID D RID B B B B B LID RID B LID D RID",
    ],
    // Уровень 38 (39)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T RIT LIT T T T T T RIT B",
      "B L N N N ROT LOT N N N ROD LOD R B",
      "B LID LOD N N ROD D D D D LB LOT R B",
      "B LIT LOT N N ROT T RIT B B L N R B",
      "B LID LOD ROD LOD N N ROT RIT B L N R B",
      "B LIT LOT R L N N N ROT RIT L N R B",
      "B L N R LID LOD N N N R L N R B",
      "B L N R B LID LOD N N ROT LOT N ROT RIT",
      "B L N R B B LID D LOD N N N ROD RID",
      "B L ROD LB T T T T LOT N N N R B",
      "B L ROT LOT N N N N N ROD LOD N R B",
      "B LID D D D D D D D RID LID D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 39 (40)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T RIT B B B B B B B B B",
      "B L N N R B B B B B B B B B",
      "B L N N ROT T T T T T T T RIT B",
      "LIT LOT N N N N N N N N N N R B",
      "LID LOD N N N N N N N N N N ROT RIT",
      "B L N N N N N N N N N N ROD RID",
      "B LID D D D D D D D LOD N N R B",
      "B B B B B B B B B L N N R B",
      "B B B B B B B B B LID LOD ROD RID B",
      "B B B B B B B B B B LID RID B B",
    ],
    // Уровень 40 (41)
    [
      "B B LIT T T T T T T T T RIT B B",
      "B LIT LOT N N N N N N N N ROT RIT B",
      "LIT LOT N N N N N ROD D D D LOD ROT RIT",
      "L N N ROD D LOD N ROT T T RIT L N R",
      "L N N R LIT LOT N N N N ROT LOT N R",
      "L N N ROT LOT N N N N N N N N R",
      "L N ROD LOD N N N N N ROD LOD N N R",
      "L N R L N N N N N R L N N R",
      "L N R L N N N N N R L N N R",
      "L N R L N N N N ROD RID L N N R",
      "L N R LID LOD N N N ROT T LOT N N R",
      "LID LOD ROT T LOT N N N N N N N ROD RID",
      "B LID LOD N N N N N N N N ROD RID B",
      "B B LID D D D D D D D D RID B B",
    ],
    // Уровень 41 (42)
    [
      "LIT T T T T T T T T T T RIT",
      "L N N N N N N N N N N R",
      "L N N N N N N N N N N R",
      "L N N N N N N N N N N R",
      "L N N N N N N N N N N R",
      "L N N N N N N N N N N R",
      "LID D D D D D D D D D D RID",
    ],
    // Уровень 42 (43)
    [
      "B B B B B B B LIT T T T T T RIT",
      "B LIT T T T T T RB LOD N N N N R",
      "B L N N N N N ROT RB LOD N N N R",
      "B L N N N N N N ROT RB LOD N N R",
      "B L N N N ROD LOD ROD LOD ROT LOT N N R",
      "B L N N ROD RID L R LID LOD N ROD LOD R",
      "B L N N ROT T LOT ROT T LOT N ROT RB RID",
      "LIT RB LOD N ROD D LOD ROD D LOD N N R B",
      "L ROT RB LOD ROT RIT L R LIT LOT N N R B",
      "L N ROT RB LOD ROT LOT ROT LOT N N N R B",
      "L N N ROT RB LOD N N N N N N R B",
      "L N N N ROT RB LOD N N N N N R B",
      "L N N N N ROT RB D D D D D RID B",
      "LID D D D D D RID B B B B B B B",
    ],
    // Уровень 43 (44)
    [
      "B B B B B B B B B B B B B B",
      "LIT T T T T T T T T T T T T RIT",
      "LID LOD N N N N N N N N N N ROD RID",
      "B L N ROD LOD ROD LOD ROD LOD ROD LOD N R B",
      "B L N R LID RID LID RID LID LB LOT N R B",
      "B L N R LIT RIT B B LIT RB LOD N R B",
      "B L N R LID RID LIT RIT LID RID L N R B",
      "B L N R B B L R B B L N R B",
      "B LID LOD ROT T T LOT ROT T T LOT ROD RID B",
      "B B LID D D D LOD N ROD D D RID B B",
      "B LIT T T T T LOT N ROT T T T RIT B",
      "B L N N N N N N N N N N R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 44 (45)
    [
      "B B B LIT RIT B B B B B",
      "B LIT T LOT ROT T T T RIT B",
      "B L N N N N N N R B",
      "B L N N N N N N R B",
      "LIT LOT N N N N N N R B",
      "LID LOD N N N N N N ROT RIT",
      "B L N N N N N N ROD RID",
      "B L N N N N N N R B",
      "B LID D D LOD ROD D D RID B",
      "B B B B LID RID B B B B",
    ],
    // Уровень 45 (46)
    [
      "B B B B B B B LIT RIT B B B B B",
      "B B B B LIT RIT LIT LOT R LIT RIT B B B",
      "B B B LIT LOT ROT LOT N ROT LOT ROT T RIT B",
      "B B B L N N N N N N N N R B",
      "B B B L N N N N N N N ROD RID B",
      "B LIT T LOT N ROD LOD ROD D LOD N R B B",
      "B L N N N R LID RID LIT LOT N R B B",
      "B L N ROD D RID B B LID LOD N R B B",
      "B LID D RID B B B B B L N R B B",
      "B B B B B B B LIT RIT L N R B B",
      "B B B B B B LIT LOT ROT LOT N R B B",
      "B B B B B B L N N N N R B B",
      "B B B B B B LID D D D D RID B B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 46 (47)
    [
      "B B B B B B B LIT RIT B B B",
      "B LIT T T T T T LOT ROT T RIT B",
      "B L N N N N N N N N R B",
      "B L N ROD D LOD ROD D LOD N ROT RIT",
      "B L ROD RID LIT LOT ROT RIT LID LOD ROD RID",
      "LIT LOT ROT T LOT N N ROT T LOT ROT RIT",
      "LID LOD ROD D LOD N N ROD D LOD ROD RID",
      "B L ROT RIT LID LOD ROD RID LIT LOT R B",
      "B L N ROT T LOT ROT T LOT N R B",
      "B L N N N N N N N N R B",
      "B LID D D D D D D D D RID B",
      "B B B B B B B B B B B B",
    ],
    // Уровень 47 (48)
    [
      "B B B B B B B B B B B B B B",
      "B B LIT RIT B B B B LIT T T RIT B B",
      "B B L ROT T T T T LOT ROD LOD R B B",
      "B LIT LOT ROD LOD ROD D LOD N ROT LOT R B B",
      "B LID LOD R L ROT RIT LID D D LOD R B B",
      "B B L R LID LOD ROT RIT LIT RIT L R B B",
      "B B L R LIT LOT N ROT LOT R L R B B",
      "B B L R LID D LOD N N R L R B B",
      "B B L ROT T RIT LID D LOD R L R B B",
      "B B L ROD LOD R LIT T LOT R L R B B",
      "B LIT LOT ROT LOT ROT LOT N N ROT LOT ROT RIT B",
      "B LID D D D D D D D D LOD ROD RID B",
      "B B B B B B B B B B LID RID B B",
    ],
    // Уровень 48 (49)
    [
      "B B B B B B B B LIT RIT B B B B",
      "B LIT RIT LIT T T T T LOT ROT T T RIT B",
      "B L ROT LOT ROD D D LOD N N N ROD RID B",
      "B L ROD D RID LIT RIT LID D LOD ROD RID B B",
      "B L ROT T T LOT ROT T T LOT ROT T RIT B",
      "B L ROD D D LOD ROD D D LOD ROD D RID B",
      "B L R LIT RIT L R LIT RIT L R LIT RIT B",
      "B L R L R L R L ROT LOT R L R B",
      "B L R L ROT LOT ROT LOT ROD LOD ROT LOT ROT RIT",
      "B L R L ROD LOD ROD LOD R LID D LOD ROD RID",
      "B L R LID RID L R L ROT T T LOT R B",
      "B L ROT T T LOT ROT LOT ROD D D LOD R B",
      "B LID D D D D D D RID B B LID RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 49 (50)
    [
      "B B B B LIT RIT B B B B B B",
      "B LIT T T LOT ROT T T RIT LIT RIT B",
      "B LID LOD N N N N N ROT LOT R B",
      "B LIT LOT N N N N N N N R B",
      "B L N N N N N N N N ROT RIT",
      "LIT LOT N N N N N N N N ROD RID",
      "LID LOD N N N N N N N N R B",
      "B L N N N N N N N N R B",
      "B L N N N N N N N ROD RID B",
      "B L ROD LOD N N N N N ROT RIT B",
      "B LID RID LID D D D LOD ROD D RID B",
      "B B B B B B B LID RID B B B",
    ],
    // Уровень 50 (51)
    [
      "B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T RIT B",
      "B L ROD D D LOD ROD LOD ROD D LOD R B",
      "B L ROT RIT LIT LOT R L R LIT LOT R B",
      "B L ROD LB RB LOD R L R L N R B",
      "B L R LID RID L R LID RID LID LOD R B",
      "B L ROT T T LOT ROT T T T LOT ROT RIT",
      "LIT LOT N ROD D LOD N ROD D LOD N ROD RID",
      "LID LOD ROD RID LIT LOT N ROT RIT LID LOD R B",
      "B LID RID LIT LOT N N N ROT RIT LID RID B",
      "B B LIT LOT N N N N N ROT RIT B B",
      "B LIT LOT N N N N N N N ROT RIT B",
      "B LID D D D D D LOD ROD D D RID B",
      "B B B B B B B LID RID B B B B",
    ],
    // Уровень 51 (52)
    [
      "B B B LIT RIT B B B B B B B",
      "B LIT T LOT ROT T T T T T RIT B",
      "B L ROD LOD ROD D D LOD ROD LOD R B",
      "B L R L ROT T RIT L R L R B",
      "B L R LID LOD ROD RID L R L R B",
      "B L ROT T LOT ROT T LOT R L R B",
      "B L ROD D D LOD ROD D RID L ROT RIT",
      "B L R LIT T LOT ROT T T LOT ROD RID",
      "B L R LID D D LOD ROD D LOD R B",
      "B L ROT T T T LOT ROT T LOT R B",
      "B LID D D D D LOD ROD D D RID B",
      "B B B B B B LID RID B B B B",
    ],
    // Уровень 52 (53)
    [
      "B B B B B B B B LIT RIT B B B B",
      "B LIT RIT B LIT T T T LOT ROT T T RIT B",
      "B L R B L N N N N N N N R B",
      "B L R B LID D LOD N N N N N R B",
      "B L ROT RIT B B LID LOD N N N N R B",
      "B L N R LIT RIT B L ROD D LOD N R B",
      "B L N ROT LOT ROT T LOT ROT T LOT N ROT RIT",
      "B L N N ROD D D LOD ROD D LOD N ROD RID",
      "B L ROD LOD ROT RIT B L R B LID LOD R B",
      "B L R L N ROT RIT L R B B LID RID B",
      "B L R L N N ROT LOT ROT T RIT B B B",
      "B L ROT LOT N N N N N N ROT T RIT B",
      "B LID D D D D LOD ROD D D D D RID B",
      "B B B B B B LID RID B B B B B B",
    ],
    // Уровень 53 (54)
    [
      "B B LIT RIT B B LIT RIT B B B B B B",
      "B LIT LOT ROT T RIT L R LIT T T T RIT B",
      "B L N N N ROT LOT ROT LOT N N N R B",
      "B L N N N N N N N N N N R B",
      "B L N N N ROD LOD ROD LOD N N N R B",
      "B LID LOD N ROD RID L R LID LOD N ROD RID B",
      "LIT T LOT N ROT T LOT ROT T LOT N ROT T RIT",
      "LID D LOD N ROD D LOD ROD D LOD N ROD D RID",
      "B LIT LOT N ROT RIT L R LIT LOT N ROT RIT B",
      "B L N N N ROT LOT ROT LOT N N N R B",
      "B L N N N N N N N N N N ROT RIT",
      "B L N N N ROD LOD ROD LOD N N N ROD RID",
      "B LID D D D RID L R LID D D D RID B",
      "B B B B B B LID RID B B B B B B",
    ],
    // Уровень 54 (55)
    [
      "B B B B B B B B B B B B",
      "B B LIT T T RIT LIT T T RIT B B",
      "LIT T LOT N N ROT LOT N N ROT RIT B",
      "LID LOD N N N N N N N N ROT RIT",
      "B L N N N N N N N N ROD RID",
      "B LID LOD N N N N N N ROD RID B",
      "B B LID D D LOD ROD D D RID B B",
      "B B LIT T T LOT ROT T T RIT B B",
      "B LIT LOT N N N N N N ROT RIT B",
      "B L N N N N N N N N ROT RIT",
      "LIT LOT N N N N N N N N ROD RID",
      "LID D LOD N N ROD LOD N N ROD RID B",
      "B B LID D D RID LID D D RID B B",
      "B B B B B B B B B B B B",
    ],
    // Уровень 55 (56)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B L N ROD D D D D D D D LOD R B",
      "B L ROD RID LIT T T T T T T LOT R B",
      "B L R LIT LOT ROD D D D D LOD N R B",
      "B L R L N ROT T T T RIT LID LOD R B",
      "B L R L N N N N N ROT RIT L R B",
      "B L R L N N N N N ROD RID L R B",
      "B L R L N ROD D D D RID LIT LOT R B",
      "B L R LID LOD ROT T T T T LOT N R B",
      "B L ROT RIT LID D D D D D D LOD R B",
      "B L N ROT T T T T T T T LOT R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 56 (57)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B L N N N ROD D D LOD N N N R B",
      "B L N N N ROT T T LOT N N N R B",
      "B L N N ROD D LOD ROD D LOD N N R B",
      "B L ROD LOD ROT T LOT ROT RIT L ROD LOD R B",
      "B L R L N N N N ROT LOT R L R B",
      "B L R L ROD LOD N N ROD LOD R L R B",
      "B L ROT LOT R LID LOD ROD RID L ROT LOT R B",
      "B L N N ROT T LOT ROT T LOT N N ROT RIT",
      "B L N N N N ROD D LOD N N N ROD RID",
      "B L N N N N ROT T LOT N N N R B",
      "B LID D LOD ROD D D D D D D D RID B",
      "B B B LID RID B B B B B B B B B",
    ],
    // Уровень 57 (58)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T RIT LIT T T T T RIT B",
      "B L N N N N ROT LOT N N N N R B",
      "B L N ROD LOD ROD D D D D LOD N R B",
      "B L N R L ROT T T T RIT L N R B",
      "B L N R L N ROD LOD N R L N R B",
      "B L ROD RID LID D RID L N R LID LOD R B",
      "B L ROT RIT LIT T T LOT N R LIT LOT R B",
      "B L N R L N ROD LOD N R L ROD RID B",
      "B L N R LID D RID LID D LB LOT R B B",
      "B L N ROT T T RIT LIT T RB LOD R B B",
      "B L ROD LOD N N ROT LOT N R L ROT RIT B",
      "B LID RID LID LOD ROD D D D RID LID D RID B",
      "B B B B LID RID B B B B B B B B",
    ],
    // Уровень 58 (59)
    [
      "B B B B B B LIT RIT B B B B B B",
      "B B B B B B L R B LIT RIT B B B",
      "B B B LIT T T LOT ROT T LOT R B B B",
      "B B LIT LOT N N N N N N ROT RIT B B",
      "B B L N N ROD LOD ROD LOD N N R B B",
      "B B L N ROD RID L R LID LOD N R B B",
      "B LIT LOT N ROT T LOT ROT T LOT N ROT T RIT",
      "B LID LOD N ROD D LOD ROD D LOD N ROD D RID",
      "B B L N ROT RIT L R LIT LOT N R B B",
      "B B L N N ROT LOT ROT LOT N N ROT RIT B",
      "B B LID LOD N N N N N N ROD D RID B",
      "B B B LID D D LOD ROD D D RID B B B",
      "B B B B B B LID RID B B B B B B",
      "B B B B B B B B B B B B B B",
    ],
    // Уровень 59 (60)
    [
      "B B B B B B B B B B B B B B",
      "B LIT RIT B B B B B B B B B B B",
      "B L ROT T T T T T T T RIT B B B",
      "B L ROD D D D D D D LOD ROT RIT B B",
      "B L R LIT T T T T T RB LOD R B B",
      "B L ROT LOT N N N N N R L R B B",
      "B L N N N N N N N R L R B B",
      "B L ROD D D D D LOD ROD RID L R B B",
      "B L ROT T RIT LIT T LOT ROT T LOT R B B",
      "B L ROD LOD ROT LOT ROD LOD N ROD D RID B B",
      "B L R LID LOD N R LID D RID LIT RIT B B",
      "B L ROT T LOT N ROT T T T LOT ROT RIT B",
      "B LID D D D LOD ROD D D D D D RID B",
      "B B B B B LID RID B B B B B B B",
    ],
    // Уровень 60 (61)
    [
      "B B B B B B B B B B B B B B",
      "B LIT T T T T T T T T T T RIT B",
      "B L N N N N N ROD D D LOD N R B",
      "B L ROD D D LOD N ROT T RIT L N R B",
      "B L R LIT T LOT N ROD D RID L N R B",
      "B L R LID D LOD N ROT T T LOT N R B",
      "B L ROT T T LOT N N N N N N R B",
      "B L N N N N N N ROD D D LOD R B",
      "B L N ROD D D LOD N ROT T RIT L R B",
      "B L N R LIT T LOT N ROD D RID L R B",
      "B L N R LID D LOD N ROT T T LOT R B",
      "B L N ROT T T LOT N N N N N R B",
      "B LID D D D D D D D D D D RID B",
      "B B B B B B B B B B B B B B",
    ],
  ];
}
